version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM_ID}
      - ADVERTISE_IP=http://${HOST_NAME}:32400/
      - PLEX_UID=${UID}
      - PLEX_GID=${GID}
    hostname: ${PLEX_HOST_NAME}
    volumes:
     - ${META_FOLDER}/config:/config 
     - ${META_FOLDER}/transcode:/transcode 
     - ${META_FOLDER}/data:/data 
     - ${MOVIES_PATH}:/movies 
     - ${TVSHOW_PATH}:/tvshows
     - ${MUSIC_PATH}/music:/music 
     - /home//external_hd:/external 
  
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
     - ${META_FOLDER}/plex/torrent_config:/config 
     - ${DOWNLOAD_PATH}:/downloads 
     - ${META_FOLDER}/torrent_watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  orca:
    image: /orca
    build:
      context: .
      dockerfile: docker_files/Dockerfile
    container_name: orca
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
      - TRANSMISSION_HOST=${HOST_NAME}
      - RSS_FEED=${RSS_FEED}
    volumes:
      - ${DOWNLOAD_PATH}:/torrent_download
      - ${MOVIES_PATH}/external_hd/Video_lib/movies:/movies
      - ${TVSHOW_PATH}:/tvshows
    restart: unless-stopped