version: '2'
services:
  orca:
    image: /orca
    build:
      context: .
    container_name: orca
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
      - TRANSMISSION_HOST=${HOST_NAME}
      - RSS_FEED=${RSS_FEED}
    volumes:
      - ${DOWNLOAD_PATH}:/torrent_download
      - ${MOVIES_PATH}/external_hd/Video_lib/movies:/movies
      - ${TVSHOW_PATH}:/tvshows
    restart: unless-stopped
